"""initial schema: all core tables + indexes from Design Document §4

Revision ID: 4d96c80b9e1a
Revises:
Create Date: 2026-08-23 18:12:19.078129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d96c80b9e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('patient', 'doctor', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('doctor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialisation', sa.String(length=100), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot_duration_minutes > 0', name='ck_doctor_slot_duration_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_profile_specialisation'), ['specialisation'], unique=False)

    op.create_table('patient_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('slot_start', sa.Time(), nullable=False),
    sa.Column('slot_end', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('held', 'confirmed', 'cancelled', 'completed', 'expired', 'leave_cancelled')", name='ck_appointment_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('idx_appt_no_double_book', ['doctor_id', 'appt_date', 'slot_start'], unique=True, postgresql_where=sa.text("status IN ('held', 'confirmed')"))
        batch_op.create_index('idx_appt_patient', ['patient_id', 'appt_date'], unique=False)

    op.create_table('doctor_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_leave', schema=None) as batch_op:
        batch_op.create_index('idx_leave_doctor_date', ['doctor_id', 'leave_date'], unique=False)

    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_google_event_id', sa.String(length=255), nullable=True),
    sa.Column('doctor_google_event_id', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("sync_status IN ('pending', 'synced', 'failed', 'permanently_failed')", name='ck_calendar_event_sync_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel = 'email'", name='ck_notification_channel'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'permanently_failed')", name='ck_notification_status'),
    sa.CheckConstraint("type IN ('confirmation', 'reminder', 'cancellation', 'leave_notice')", name='ck_notification_type'),
    sa.CheckConstraint('retry_count >= 0', name='ck_notification_retry_count_nonneg'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('raw_symptoms', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('suggested_questions', sa.JSON(), nullable=True),
    sa.Column('llm_status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("llm_status IN ('pending', 'ok', 'failed')", name='ck_symptom_summary_llm_status'),
    sa.CheckConstraint("urgency IS NULL OR urgency IN ('Low', 'Medium', 'High')", name='ck_symptom_summary_urgency'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('visit_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=False),
    sa.Column('patient_friendly_summary', sa.Text(), nullable=True),
    sa.Column('llm_status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("llm_status IN ('pending', 'ok', 'failed')", name='ck_visit_note_llm_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('prescription_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_note_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_days > 0', name='ck_prescription_duration_positive'),
    sa.ForeignKeyConstraint(['visit_note_id'], ['visit_note.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_item_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name='ck_medication_reminder_status'),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_reminder', schema=None) as batch_op:
        batch_op.create_index('idx_reminder_due', ['status', 'scheduled_for'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminder', schema=None) as batch_op:
        batch_op.drop_index('idx_reminder_due')

    op.drop_table('medication_reminder')
    op.drop_table('prescription_item')
    op.drop_table('visit_note')
    op.drop_table('symptom_summary')
    op.drop_table('notification')
    op.drop_table('calendar_event')
    with op.batch_alter_table('doctor_leave', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_doctor_date')

    op.drop_table('doctor_leave')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('idx_appt_patient')
        batch_op.drop_index('idx_appt_no_double_book', postgresql_where=sa.text("status IN ('held', 'confirmed')"))

    op.drop_table('appointment')
    op.drop_table('patient_profile')
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_profile_specialisation'))

    op.drop_table('doctor_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
